ports:
  grafana: 3100  # Port de Grafana
  prometheus: 9090  # Port de Prometheus
  bentoml_service: 3000  # Port utilisé par BentoML
  ML_flow: 8080 # Port utilisé par MLflow
  drift_monitoring_api: 8088  # Port pour le Drift Monitoring

