version: '3'

services:
  mlflow:
    build:
      context: ..
      dockerfile: mlflow/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/app/mlflow  # Monte tout le répertoire mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:8080
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/mlflow/mlartifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /app/mlflow/mlartifacts
      --host 0.0.0.0
      --port 8080