version: '3'

services:
  mlflow:
    build:
      context: ..  # Context au niveau racine du projet
      dockerfile: mlflow/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlruns:/mlruns
      - ..:/app/data_pipeline
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:8080
      - ARTIFACT_ROOT=/mlartifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3